version: '2'
services:
  postgres:
    container_name: friday-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5442:5432
